from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from datetime import date

def create_medicine_poster(patient_name, medicines, filename="medicine_reminder.pdf"):
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # Background color
    c.setFillColor(colors.HexColor("#EBF5FB"))
    c.rect(0, 0, width, height, fill=1, stroke=0)

    # Title banner
    c.setFillColor(colors.HexColor("#2E86C1"))
    c.rect(0, height - 120, width, 120, fill=1, stroke=0)

    # Title text
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 32)
    c.drawCentredString(width/2, height - 60, "💊 Daily Medicine Reminder")
    c.setFont("Helvetica", 18)
    c.drawCentredString(width/2, height - 90, f"Patient: {patient_name}")

    # Date
    today = date.today().strftime("%d %B %Y")
    c.setFillColor(colors.HexColor("#2E86C1"))
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width/2, height - 140, f"Date: {today}")

    # Medicine boxes
    y_position = height - 180

    for i, med in enumerate(medicines):
        # Box background
        box_color = colors.HexColor("#D6EAF8") if i % 2 == 0 else colors.HexColor("#D5F5E3")
        c.setFillColor(box_color)
        c.roundRect(40, y_position - 90, width - 80, 85, 10, fill=1, stroke=0)

        # Medicine number
        c.setFillColor(colors.HexColor("#2E86C1"))
        c.setFont("Helvetica-Bold", 28)
        c.drawString(60, y_position - 35, f"{i+1}.")

        # Medicine name
        c.setFillColor(colors.HexColor("#1A252F"))
        c.setFont("Helvetica-Bold", 24)
        c.drawString(100, y_position - 35, med['name'])

        # Dose and timing
        c.setFont("Helvetica", 20)
        c.setFillColor(colors.HexColor("#2C3E50"))
        c.drawString(100, y_position - 65, f"Dose: {med['tablets_per_day']} tablet(s)   |   Time: {med['timing']}")

        # Stock warning
        if med['total_tablets'] <= 2:
            c.setFillColor(colors.red)
            c.setFont("Helvetica-Bold", 18)
            c.drawString(100, y_position - 85, "🚨 URGENT: Stock almost finished!")
        elif med['total_tablets'] <= 5:
            c.setFillColor(colors.HexColor("#E67E22"))
            c.setFont("Helvetica-Bold", 18)
            c.drawString(100, y_position - 85, f"⚠️ Only {med['total_tablets']} tablets left - Reorder soon!")

        y_position -= 110

    # Footer
    c.setFillColor(colors.HexColor("#2E86C1"))
    c.rect(0, 0, width, 50, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, 18, "Generated by MediCare AI Agent 💙 Stay Healthy!")

    c.save()
    print(f"✅ Poster saved as {filename}")
    print(f"📁 Location: MediCare_Agent folder")

# Test with your medicines
medicines = [
    {
        'name': 'Cap. D-Pearl 60k',
        'tablets_per_day': 1,
        'timing': 'Night (Weekly)',
        'total_tablets': 8
    },
    {
        'name': 'T. Cetirizine 10mg',
        'tablets_per_day': 1,
        'timing': 'Night',
        'total_tablets': 5
    },
    {
        'name': 'Cap. Omeprazole 20mg',
        'tablets_per_day': 1,
        'timing': 'Morning (Before food)',
        'total_tablets': 5
    }
]

create_medicine_poster(
    patient_name="Jincy Varghese",
    medicines=medicines
)