import os
import smtplib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date
from dotenv import load_dotenv
from google import genai

load_dotenv()

EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=GEMINI_API_KEY)

def generate_weekly_report(patient_name, medicines):
    print("🤖 AI is generating weekly report...")

    medicine_summary = ""
    for med in medicines:
        medicine_summary += f"""
        - {med['name']}: {med['tablets_per_day']} tablet(s) per day, 
          {med['total_tablets']} tablets remaining, 
          Timing: {med['timing']}
        """

    prompt = f"""
    You are a caring medical AI assistant.
    Generate a warm, detailed weekly health report for the family of {patient_name}.
    
    Medicine details this week:
    {medicine_summary}
    
    Include in the report:
    1. Weekly medicine consumption summary
    2. Stock status and reorder alerts
    3. 3 simple health tips for elderly people
    4. An encouraging message for the patient
    5. Action items for the family
    
    Write in a warm, clear, easy to understand tone.
    Format it nicely with sections and emojis.
    """

    time.sleep(2)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

def send_weekly_report(patient_name, medicines, family_email):
    print("=== GENERATING WEEKLY REPORT ===\n")

    # Generate report using AI
    report_content = generate_weekly_report(patient_name, medicines)

    today = date.today().strftime("%d %B %Y")

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; font-size: 16px; 
                 max-width: 700px; margin: auto; padding: 20px;">
        
        <div style="background-color: #2E86C1; padding: 20px; 
                    border-radius: 10px; text-align: center;">
            <h1 style="color: white; margin: 0;">🏥 MediCare Weekly Report</h1>
            <p style="color: white; margin: 5px 0;">Patient: {patient_name}</p>
            <p style="color: white; margin: 5px 0;">Week ending: {today}</p>
        </div>
        
        <div style="background-color: #f8f9fa; padding: 20px; 
                    border-radius: 10px; margin-top: 20px;">
            {report_content.replace(chr(10), '<br>')}
        </div>
        
        <div style="background-color: #2E86C1; padding: 15px; 
                    border-radius: 10px; margin-top: 20px; text-align: center;">
            <p style="color: white; margin: 0;">
                Generated by MediCare AI Agent 💙
            </p>
            <p style="color: white; margin: 5px 0; font-size: 12px;">
                Keeping your loved ones healthy and happy!
            </p>
        </div>
        
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🏥 Weekly Medicine Report - {patient_name} - {today}"
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = family_email
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.sendmail(EMAIL_ADDRESS, family_email, msg.as_string())
        print(f"✅ Weekly report sent to {family_email}!")
    except Exception as e:
        print(f"❌ Error: {e}")

# Test
medicines = [
    {
        'name': 'Cap. D-Pearl 60k',
        'tablets_per_day': 1,
        'timing': 'Night (Weekly)',
        'total_tablets': 8
    },
    {
        'name': 'T. Cetirizine 10mg',
        'tablets_per_day': 1,
        'timing': 'Night',
        'total_tablets': 5
    },
    {
        'name': 'Cap. Omeprazole 20mg',
        'tablets_per_day': 1,
        'timing': 'Morning (Before food)',
        'total_tablets': 5
    }
]

send_weekly_report(
    patient_name="Jincy Varghese",
    medicines=medicines,
    family_email="jincy.builds@gmail.com"
)